### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by idnemo** [getnamo/tensorflow-ue4#11]
Try to build a android version for Mnist example, but failed.

[UAT_Log.txt](https://github.com/getnamo/tensorflow-ue4/files/1320534/UAT_Log.txt)
[Cook-2017.09.21-16.28.20.txt](https://github.com/getnamo/tensorflow-ue4/files/1320535/Cook-2017.09.21-16.28.20.txt)

![image](https://user-images.githubusercontent.com/17142612/30687448-de780416-9eed-11e7-9715-9ca6a80b8397.png)

**Comment by getnamo** [comment]
For the current version there are some windows dependencies which may stop other platforms from building. Will 

The dependencies are: 
- [socketio-client-ue4](https://github.com/getnamo/socketio-client-ue4) plugin. Still missing prebuild libraries for linux and android (https://github.com/getnamo/socketio-client-ue4/issues/21)
- Pip uses windows commandline to work asynchronously. I do plan at some point to make it platform agnostic, added issue for this problem (https://github.com/getnamo/tensorflow-ue4/issues/12)

You can work around the first issue by extracting SIOJson from the socketio plugin, that part is completely platform agnostic.

The second issue can be solved by installing your embedded python and pip dependencies manually.

Looking through your logs it appears you get this error as your current block: https://github.com/20tab/UnrealEnginePython/issues/149 which is generally considered a non issue for editor builds. Just add an empty ue_site.py in the correct place.

**Comment by idnemo** [comment]
after add ue_site.py, it packed successfully. After I install it on my android phone, it crash in the beginning. I tried to remove SIOJson from SocketIOClient.uplugin, still get those loading error

09-22 14:35:54.729 11588 11604 D UE4     : LogStreaming: Error: Couldn't find file for package /Script/SocketIOClient requested by async loading code. NameToLoad: /Script/SocketIOClient
09-22 14:35:54.729 11588 11604 D UE4     : 
09-22 14:35:54.729 11588 11604 D UE4     : [2017.09.22-06.35.54:729][  0]LogStreaming: Error: Couldn't find file for package /Script/SocketIOClient requested by async loading code. NameToLoad: /Script/SocketIOClient
09-22 14:35:54.729 11588 11604 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.729 11588 11604 D UE4     : 
09-22 14:35:54.729 11588 11604 D UE4     : [2017.09.22-06.35.54:729][  0]LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.730 11588 11604 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-22 14:35:54.730 11588 11604 D UE4     : 
09-22 14:35:54.730 11588 11604 D UE4     : [2017.09.22-06.35.54:730][  0]LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-22 14:35:54.730 11588 11604 D UE4     : LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/TensorflowComponent' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-22 14:35:54.730 11588 11604 D UE4     : 
09-22 14:35:54.730 11588 11604 D UE4     : [2017.09.22-06.35.54:730][  0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/TensorflowComponent' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-22 14:35:54.730 11588 11604 D UE4     : LogStreaming: Error: Couldn't find file for package /TensorFlow/TensorflowComponent requested by async loading code. NameToLoad: /TensorFlow/TensorflowComponent
09-22 14:35:54.730 11588 11604 D UE4     : 
09-22 14:35:54.730 11588 11604 D UE4     : [2017.09.22-06.35.54:730][  0]LogStreaming: Error: Couldn't find file for package /TensorFlow/TensorflowComponent requested by async loading code. NameToLoad: /TensorFlow/TensorflowComponent
09-22 14:35:54.730 11588 11604 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.730 11588 11604 D UE4     : 
09-22 14:35:54.730 11588 11604 D UE4     : [2017.09.22-06.35.54:730][  0]LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.730 11588 11604 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-22 14:35:54.730 11588 11604 D UE4     : 
09-22 14:35:54.731 11588 11604 D UE4     : [2017.09.22-06.35.54:731][  0]LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-22 14:35:54.737 11588 11604 D UE4     : LogStreaming: Error: Couldn't find file for package /Script/TensorFlow requested by async loading code. NameToLoad: /Script/TensorFlow
09-22 14:35:54.737 11588 11604 D UE4     : 
09-22 14:35:54.738 11588 11604 D UE4     : [2017.09.22-06.35.54:737][  0]LogStreaming: Error: Couldn't find file for package /Script/TensorFlow requested by async loading code. NameToLoad: /Script/TensorFlow
09-22 14:35:54.738 11588 11604 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.738 11588 11604 D UE4     : 
09-22 14:35:54.738 11588 11604 D UE4     : [2017.09.22-06.35.54:738][  0]LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.738 11588 11604 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/StrokeTextureComponent
09-22 14:35:54.738 11588 11604 D UE4     : 
09-22 14:35:54.738 11588 11604 D UE4     : [2017.09.22-06.35.54:738][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/StrokeTextureComponent
09-22 14:35:54.745 11588 11604 D UE4     : LogStreaming: Error: Couldn't find file for package /Script/SIOJson requested by async loading code. NameToLoad: /Script/SIOJson
09-22 14:35:54.745 11588 11604 D UE4     : 
09-22 14:35:54.746 11588 11604 D UE4     : [2017.09.22-06.35.54:746][  0]LogStreaming: Error: Couldn't find file for package /Script/SIOJson requested by async loading code. NameToLoad: /Script/SIOJson
09-22 14:35:54.746 11588 11604 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.746 11588 11604 D UE4     : 
09-22 14:35:54.746 11588 11604 D UE4     : [2017.09.22-06.35.54:746][  0]LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.746 11588 11604 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-22 14:35:54.746 11588 11604 D UE4     : 
09-22 14:35:54.746 11588 11604 D UE4     : [2017.09.22-06.35.54:746][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-22 14:35:54.747 11588 11604 D UE4     : LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/ImageStruct' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-22 14:35:54.747 11588 11604 D UE4     : 
09-22 14:35:54.747 11588 11604 D UE4     : [2017.09.22-06.35.54:747][  0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/ImageStruct' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-22 14:35:54.747 11588 11604 D UE4     : LogStreaming: Error: Couldn't find file for package /TensorFlow/ImageStruct requested by async loading code. NameToLoad: /TensorFlow/ImageStruct
09-22 14:35:54.747 11588 11604 D UE4     : 
09-22 14:35:54.747 11588 11604 D UE4     : [2017.09.22-06.35.54:747][  0]LogStreaming: Error: Couldn't find file for package /TensorFlow/ImageStruct requested by async loading code. NameToLoad: /TensorFlow/ImageStruct
09-22 14:35:54.747 11588 11604 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.747 11588 11604 D UE4     : 
09-22 14:35:54.747 11588 11604 D UE4     : [2017.09.22-06.35.54:747][  0]LogStreaming: Error: Found 1 dependent packages...
09-22 14:35:54.747 11588 11604 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-22 14:35:54.747 11588 11604 D UE4     : 
09-22 14:35:54.747 11588 11604 D UE4     : [2017.09.22-06.35.54:747][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error: ****DumpDependencies [Dependencies]:
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error: ****DumpDependencies [Dependencies]:
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:     Export 159 SocketIOClient_GEN_VARIABLE
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error:     Export 159 SocketIOClient_GEN_VARIABLE
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:     Linker is ../../../TensorFlowExamples/Content/ExampleAssets/Blueprints/ConnectedTFMnistActor.uasset
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error:     Linker is ../../../TensorFlowExamples/Content/ExampleAssets/Blueprints/ConnectedTFMnistActor.uasset
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:         Dep S_BEFORE_S Export   139    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error:         Dep S_BEFORE_S Export   139    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:         Dep S_BEFORE_C Import    41   SocketIOClientComponent
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error:         Dep S_BEFORE_C Import    41   SocketIOClientComponent
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:         Dep S_BEFORE_C Import   125   Default__SocketIOClientComponent
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.778 11588 11604 D UE4     : [2017.09.22-06.35.54:778][  0]LogStreaming: Error:         Dep S_BEFORE_C Import   125   Default__SocketIOClientComponent
09-22 14:35:54.778 11588 11604 D UE4     : LogStreaming: Error:         Dep C_BEFORE_C Export   139    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-22 14:35:54.778 11588 11604 D UE4     : 
09-22 14:35:54.779 11588 11604 D UE4     : [2017.09.22-06.35.54:779][  0]LogStreaming: Error:         Dep C_BEFORE_C Export   139    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-22 14:35:54.788 11588 11604 D UE4     : Fatal error: [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 3004] 
09-22 14:35:54.788 11588 11604 D UE4     : Missing Dependency, request for SocketIOClientComponent but it hasn't been created yet.
09-22 14:35:54.788 11588 11604 D UE4     : [2017.09.22-06.35.54:788][  0]Assertion failed: Assertion failed:  [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 3004] 
09-22 14:35:54.788 11588 11604 D UE4     : Missing Dependency, request for SocketIOClientComponent but it hasn't been created yet.
09-22 14:35:54.798 11588 11604 D UE4     : [2017.09.22-06.35.54:798][  0]LogWindows: FAndroidMisc::RequestExit(1)
09-22 14:35:54.799 11588 11604 I art     : System.exit called, status: 0
09-22 14:35:54.800 11588 11604 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.

[logcat3.txt](https://github.com/getnamo/tensorflow-ue4/files/1323651/logcat3.txt)

**Comment by getnamo** [comment]
It should be the other way, keep SIOJson, remove SocketIOClient module from the  SocketIOClient.uplugin. If you do this you will have to remove the socketioclient component from the ConnectedMnistActor example if you plan to try it out since it uses this component to receive strokes from the browser.

**Comment by idnemo** [comment]
After I use you solution, the SocketIOClient errors are gone. But it still have tensorflowcomponent couldn't find issue.

09-27 16:12:31.034  4283  4299 D UE4     : LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/TensorflowComponent' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-27 16:12:31.034  4283  4299 D UE4     : 
09-27 16:12:31.034  4283  4299 D UE4     : [2017.09.27-08.12.31:034][  0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/TensorflowComponent' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-27 16:12:31.035  4283  4299 D UE4     : LogStreaming: Error: Couldn't find file for package /TensorFlow/TensorflowComponent requested by async loading code. NameToLoad: /TensorFlow/TensorflowComponent
09-27 16:12:31.035  4283  4299 D UE4     : 
09-27 16:12:31.035  4283  4299 D UE4     : [2017.09.27-08.12.31:035][  0]LogStreaming: Error: Couldn't find file for package /TensorFlow/TensorflowComponent requested by async loading code. NameToLoad: /TensorFlow/TensorflowComponent
09-27 16:12:31.035  4283  4299 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.035  4283  4299 D UE4     : 
09-27 16:12:31.035  4283  4299 D UE4     : [2017.09.27-08.12.31:035][  0]LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.035  4283  4299 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-27 16:12:31.035  4283  4299 D UE4     : 
09-27 16:12:31.036  4283  4299 D UE4     : [2017.09.27-08.12.31:036][  0]LogStreaming: Error:   /Game/ExampleAssets/Maps/Mnist
09-27 16:12:31.049  4283  4299 D UE4     : LogStreaming: Error: Couldn't find file for package /Script/TensorFlow requested by async loading code. NameToLoad: /Script/TensorFlow
09-27 16:12:31.050  4283  4299 D UE4     : 
09-27 16:12:31.050  4283  4299 D UE4     : [2017.09.27-08.12.31:050][  0]LogStreaming: Error: Couldn't find file for package /Script/TensorFlow requested by async loading code. NameToLoad: /Script/TensorFlow
09-27 16:12:31.050  4283  4299 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.050  4283  4299 D UE4     : 
09-27 16:12:31.050  4283  4299 D UE4     : [2017.09.27-08.12.31:050][  0]LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.050  4283  4299 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/StrokeTextureComponent
09-27 16:12:31.050  4283  4299 D UE4     : 
09-27 16:12:31.051  4283  4299 D UE4     : [2017.09.27-08.12.31:051][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/StrokeTextureComponent
09-27 16:12:31.067  4283  4299 D UE4     : LogStreaming: Error: Couldn't find file for package /Script/SIOJson requested by async loading code. NameToLoad: /Script/SIOJson
09-27 16:12:31.067  4283  4299 D UE4     : 
09-27 16:12:31.067  4283  4299 D UE4     : [2017.09.27-08.12.31:067][  0]LogStreaming: Error: Couldn't find file for package /Script/SIOJson requested by async loading code. NameToLoad: /Script/SIOJson
09-27 16:12:31.067  4283  4299 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.067  4283  4299 D UE4     : 
09-27 16:12:31.067  4283  4299 D UE4     : [2017.09.27-08.12.31:067][  0]LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.067  4283  4299 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-27 16:12:31.067  4283  4299 D UE4     : 
09-27 16:12:31.068  4283  4299 D UE4     : [2017.09.27-08.12.31:067][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-27 16:12:31.069  4283  4299 D UE4     : LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/ImageStruct' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-27 16:12:31.069  4283  4299 D UE4     : 
09-27 16:12:31.069  4283  4299 D UE4     : [2017.09.27-08.12.31:069][  0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/TensorFlow/ImageStruct' is not a standard unreal filename or a long path name. Reason: Path does not start with a valid root. Path must begin with: '/Engine/', '/Game/', '/Paper2D/', '/OculusVR/', '/SteamVR/', '/Config/', '/Script/', '/Memory/', or '/Temp/'
09-27 16:12:31.069  4283  4299 D UE4     : LogStreaming: Error: Couldn't find file for package /TensorFlow/ImageStruct requested by async loading code. NameToLoad: /TensorFlow/ImageStruct
09-27 16:12:31.069  4283  4299 D UE4     : 
09-27 16:12:31.070  4283  4299 D UE4     : [2017.09.27-08.12.31:069][  0]LogStreaming: Error: Couldn't find file for package /TensorFlow/ImageStruct requested by async loading code. NameToLoad: /TensorFlow/ImageStruct
09-27 16:12:31.070  4283  4299 D UE4     : LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.070  4283  4299 D UE4     : 
09-27 16:12:31.070  4283  4299 D UE4     : [2017.09.27-08.12.31:070][  0]LogStreaming: Error: Found 1 dependent packages...
09-27 16:12:31.070  4283  4299 D UE4     : LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-27 16:12:31.070  4283  4299 D UE4     : 
09-27 16:12:31.070  4283  4299 D UE4     : [2017.09.27-08.12.31:070][  0]LogStreaming: Error:   /Game/ExampleAssets/Blueprints/ConnectedTFMnistActor
09-27 16:12:31.113  4283  4299 D UE4     : LogStreaming: Error: ****DumpDependencies [Dependencies]:
09-27 16:12:31.113  4283  4299 D UE4     : 
09-27 16:12:31.113  4283  4299 D UE4     : [2017.09.27-08.12.31:113][  0]LogStreaming: Error: ****DumpDependencies [Dependencies]:
09-27 16:12:31.113  4283  4299 D UE4     : LogStreaming: Error:     Export 155 TensorflowComponent_GEN_VARIABLE
09-27 16:12:31.113  4283  4299 D UE4     : 
09-27 16:12:31.113  4283  4299 D UE4     : [2017.09.27-08.12.31:113][  0]LogStreaming: Error:     Export 155 TensorflowComponent_GEN_VARIABLE
09-27 16:12:31.113  4283  4299 D UE4     : LogStreaming: Error:     Linker is ../../../TensorFlowExamples/Content/ExampleAssets/Blueprints/ConnectedTFMnistActor.uasset
09-27 16:12:31.113  4283  4299 D UE4     : 
09-27 16:12:31.113  4283  4299 D UE4     : [2017.09.27-08.12.31:113][  0]LogStreaming: Error:     Linker is ../../../TensorFlowExamples/Content/ExampleAssets/Blueprints/ConnectedTFMnistActor.uasset
09-27 16:12:31.113  4283  4299 D UE4     : LogStreaming: Error:         Dep S_BEFORE_S Export   134    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-27 16:12:31.113  4283  4299 D UE4     : 
09-27 16:12:31.113  4283  4299 D UE4     : [2017.09.27-08.12.31:113][  0]LogStreaming: Error:         Dep S_BEFORE_S Export   134    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-27 16:12:31.114  4283  4299 D UE4     : LogStreaming: Error:         Dep S_BEFORE_C Import     9   TensorflowComponent_C
09-27 16:12:31.114  4283  4299 D UE4     : 
09-27 16:12:31.114  4283  4299 D UE4     : [2017.09.27-08.12.31:114][  0]LogStreaming: Error:         Dep S_BEFORE_C Import     9   TensorflowComponent_C
09-27 16:12:31.114  4283  4299 D UE4     : LogStreaming: Error:         Dep S_BEFORE_C Import   126   Default__TensorflowComponent_C
09-27 16:12:31.114  4283  4299 D UE4     : 
09-27 16:12:31.114  4283  4299 D UE4     : [2017.09.27-08.12.31:114][  0]LogStreaming: Error:         Dep S_BEFORE_C Import   126   Default__TensorflowComponent_C
09-27 16:12:31.114  4283  4299 D UE4     : LogStreaming: Error:         Dep C_BEFORE_C Export   134    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-27 16:12:31.114  4283  4299 D UE4     : 
09-27 16:12:31.114  4283  4299 D UE4     : [2017.09.27-08.12.31:114][  0]LogStreaming: Error:         Dep C_BEFORE_C Export   134    ConnectedTFMnistActor_C     (class BlueprintGeneratedClass)
09-27 16:12:31.123  4283  4299 D UE4     : Fatal error: [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 3004] 
09-27 16:12:31.123  4283  4299 D UE4     : Missing Dependency, request for TensorflowComponent_C but it hasn't been created yet.
09-27 16:12:31.123  4283  4299 D UE4     : [2017.09.27-08.12.31:123][  0]Assertion failed: Assertion failed:  [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 3004] 
09-27 16:12:31.123  4283  4299 D UE4     : Missing Dependency, request for TensorflowComponent_C but it hasn't been created yet.
09-27 16:12:31.133  4283  4299 D UE4     : [2017.09.27-08.12.31:133][  0]LogWindows: FAndroidMisc::RequestExit(1)
09-27 16:12:31.134  4283  4299 I art     : System.exit called, status: 0

**Comment by getnamo** [comment]
note: Best approach for android platform would be some form of Tensorflow Lite. Perhaps a separate inference optimized plugin?

related issue: https://github.com/getnamo/tensorflow-ue4/issues/18

**Comment by getnamo** [comment]
will be pursued in https://github.com/getnamo/tensorflow-native-ue4/issues/2 instead of here
