### ISSUE TITLE
how to use in self-compiled UE4

### ISSUE THREAD

**Issue by sc1991327** [getnamo/tensorflow-ue4#14]
I use UE4.15 compiled by my self. The problem is I used v0.2.0 for UE4.15 and v0.4.1 for UE4.17 all failed. the python can not include tendoeflow module. What can I do?
How to use the git cloning? could you show the detail step by step, thank you.

**Comment by getnamo** [comment]
Instructions are found here https://github.com/getnamo/tensorflow-ue4#note-on-git-cloning

Essentially you need to ensure you download the python plugin binaries (direct link https://github.com/getnamo/UnrealEnginePython/releases)  which contain the prebuilt embedded python v3.5. Then when you recompile your project with the plugin for your engine source it should work.

**Comment by sc1991327** [comment]
the right compiled python module is:
![image](https://user-images.githubusercontent.com/5671048/31757020-ab424c6c-b4d9-11e7-907e-e9498f2753ee.png)
and I always compiled python module in 4.15 with v0.2.0 is:
![image](https://user-images.githubusercontent.com/5671048/31757054-cad501d2-b4d9-11e7-8514-a777bc0d299f.png)
What's the problem about this?

**Comment by getnamo** [comment]
If you want to use a newer version of tensorflow, you can just change https://github.com/getnamo/tensorflow-ue4/blob/master/Content/Scripts/upymodule.json to that version and relaunch your project. It should pull the relevant modules. I generally will check and update tensorflow versions on new engine updates.

**Comment by sc1991327** [comment]
I find the problem is my network environment block the python download modules, so failed to install Tensorflow. Thank you for your help.

**Comment by getnamo** [comment]
Glad you found the problem :), closing issue.
