### ISSUE TITLE
Failed to load the native TensorFlow runtime after UE restart.

### ISSUE THREAD

**Issue by roadstargames** [getnamo/tensorflow-ue4#17]
**Steps to reproduce**:
1) Unzip plugins from tensorflow-ue4.17-v0.4.1-gpu.7z 
2) Open TensorFlowExamples.uproject in UE and Play. Everythings run fine.
3) Close Unreal Editor.
4) Re-open the project and Play. TensorFlow won't work anymore.
5) Check Python Console and see the red error message about TensorFlow runtime failed to load.

**Temporary solution**:
Delete "Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\" folder before re-open .uproject

UnrealEnginePython plugin will have to re-install modules.

**Comment by getnamo** [comment]
Is it related to the first time run missing packages?
https://github.com/getnamo/tensorflow-ue4#no-module-named-tensorflow

Currently needs to download the tf packages first (take about 1-5min) and then restart the project before it's ready to use.

**Comment by roadstargames** [comment]
Not really. I did full install of tensorflow (here the part of my own list):

3) Run: pip3 install --upgrade tensorflow
4) Check installation:
py
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))

So, everything works OK.

And I am not getting the error after first run. I can play the map as many times as I want untill closing UE. And after re-open UE I will get described problem. 

Let me to add some links to screenshots as soon as I will get home tonight.

**Comment by getnamo** [comment]
what does your https://github.com/getnamo/tensorflow-ue4/blob/master/Content/Scripts/upymodule.json say? I wonder if it's trying to pull the -gpu version instead of cpu if you have the regular version installed.

**Comment by getnamo** [comment]
Closing due to age and lack of activity. Re-open if problem persists in new releases.
