### ISSUE TITLE
tensorflow lite support

### ISSUE THREAD

**Issue by getnamo** [getnamo/tensorflow-ue4#18]
See https://www.tensorflow.org/mobile/tflite/

Ideally bind the C++ api and expose to blueprint along with TFLite converter.

Wishlist for now.

**Comment by getnamo** [comment]
also related:
- libtensorflow dll bind for C api inference
- TensorRT if they ever release a windows build allowing tensorcore use.

**Comment by moothyknight** [comment]
Yes please! Wish I knew how to help!

**Comment by getnamo** [comment]
Tensorflow lite will likely reside in the native version of the plugin, work tracked here: https://github.com/getnamo/tensorflow-native-ue4

Resources: 
- tensorflow lite build hints https://zimenglyu.com/en/ml/android/tensorflow/2018/11/27/tflite-android-ndk-eng.html, appears to still require a bazel build process. 
- models: https://www.tensorflow.org/lite/models
- reference: old TfLiteCameraDemo apk with prebuilt .so (https://storage.googleapis.com/download.tensorflow.org/deps/tflite/TfLiteCameraDemo.apk)

**Comment by getnamo** [comment]
Closing issue, effort toward this issue will be made here: https://github.com/getnamo/tensorflow-native-ue4/issues/2
