### ISSUE TITLE
TFActor.uasset not visible 

### ISSUE THREAD

**Issue by jresch** [getnamo/tensorflow-ue4#2]
In UE 4.14.3 TFActor.uasset not visible in Content Explorer

**Comment by getnamo** [comment]
I'm assuming you're referring to: https://github.com/getnamo/tensorflow-ue4-mnist-example/blob/master/Content/TFActor.uasset ?
The project's TFActor may have been renamed TFTestActor and this may be a redirector. 

Note that it's currently just a demo actor for the MNIST classification example project and early BP Tensorflow API hasn't been really explored properly yet. Currently working through automatic pip dependency resolution before tackling early APIs. Any particular use cases you think should be available through blueprint APIs?
