### ISSUE TITLE
OpenAI integration

### ISSUE THREAD

**Issue by paulmac00** [getnamo/tensorflow-ue4#21]
Hello,

I must thank you from the bottom of my heart! This plug in is absolutely fantastic and I have been playing with it for a couple weeks now. Amazing job and I can't thank you enough for publishing this. 

I am a machine learning noob but looking to pick up some skills. I am working on integrating the OpenAI work into this but I am having some difficulty. 

Do you have any pointers that might be of help? 

And can/how do you run the pip command to install packages? 

Best,
Paul

**Comment by getnamo** [comment]
Glad it's useful :)

There are two parts that come into mind when I think of OpenAI, the [gym](https://github.com/openai/gym) and the [baselines](https://github.com/openai/baselines).

It would be great to have samples from the baseline working in ue4 maybe use e.g. the [deepq](https://github.com/openai/baselines/tree/master/baselines/deepq) model for reinforcement learning. In the examples repository there is a qlearning branch found here (https://github.com/getnamo/tensorflow-ue4-examples/tree/qlearn) which has a basic pong map with qlearning. It should mostly work out of the box, but the model hasn't been successfully trained yet. Maybe using OpenAI there would be useful.

Regarding the gym, this is essentially their 'world' replacement which is functionally similar to what ue4 is, but generally for simpler games. As long as the gym can be [installed on windows](https://github.com/openai/gym/issues/11#issuecomment-362761445) we should be able to use pip to get things working. I'm not sure how you'd like to use this part in ue4 though?

In terms of pip install, there are many ways to use it. The easiest is perhaps to just add a line in https://github.com/getnamo/tensorflow-ue4/blob/master/Content/Scripts/upymodule.json with your package name and version, when you re-launch your project it will automatically install all packages in that json file. The second way is to open your python console:

![image](https://user-images.githubusercontent.com/542365/36910976-166a0d6c-1e3a-11e8-85ae-d8b79815fe18.png)

you can then just type python commands. There is a pip wrapper called [upypip](https://github.com/getnamo/UnrealEnginePython/blob/master/Content/Scripts/upypip.py) which uses commandline so it doesn't block the thread while installing to use it type e.g.
```
import upypip
pip = upypip.pip
```
then just type e.g. pip.list() to see all the installed dependencies. This is usually what it looks like by default with tensorflow installed

![image](https://user-images.githubusercontent.com/542365/36911201-b8a49e26-1e3a-11e8-92bc-56da59245b77.png)

and then you can just type pip.install('gym') and it appears to resolve and install after about a minute

![image](https://user-images.githubusercontent.com/542365/36911311-0f68af90-1e3b-11e8-9d99-b31246a90eb2.png)

but trying to use it with e.g. an atari game example causes errors

![image](https://user-images.githubusercontent.com/542365/36911423-65363b5e-1e3b-11e8-80fd-9b87f285437e.png)

fixing that by installing the atari pre-requisites didn't seem to work either

![image](https://user-images.githubusercontent.com/542365/36911485-8cb5bc4a-1e3b-11e8-9b0c-b10f13ee21be.png)

may need to follow this comment to get it to work properly https://github.com/openai/gym/issues/11#issuecomment-362761445

That should get you all the parts you need to figure out what you want working with tensorflow and openai in ue4 and how to approach it.

**Comment by getnamo** [comment]
Closed, question is more suitable to https://github.com/getnamo/tensorflow-ue4-examples or the forum thread: https://forums.unrealengine.com/community/work-in-progress/1357673-tensorflow
