### ISSUE TITLE
Incompatible with ue4.19.0

### ISSUE THREAD

**Issue by ParmuSingh** [getnamo/tensorflow-ue4#23]
Plugins cannot be added in my version of ue4.

Screenshot : https://i.imgur.com/lRWWZGU.png

**Comment by getnamo** [comment]
For 4.19 did you download from https://github.com/getnamo/tensorflow-ue4/releases/tag/0.8.0 either tensorflow-ue4.19-v0.8.0-cpu.7z or tensorflow-ue4.19-v0.8.0-gpu.7z and follow the instructions outlined in https://github.com/getnamo/tensorflow-ue4-examples#setup?

**Comment by ParmuSingh** [comment]
yes. I've tried both cpu and gpu and followed the instructions.

**Comment by ParmuSingh** [comment]
Tested with 4.17.2 with proper plugins. Its working now. Thank you.
