### ISSUE TITLE
Retrain not working?

### ISSUE THREAD

**Issue by bernhardrieder** [getnamo/tensorflow-ue4#26]
I was wondering if I'm using the retraining variable the right way --> I'm setting it to True when i want to force the API to retrain but it never happens! And I couldn't find the code part where it'd trigger a retraining? Therefore, I decided to do it manually with `self.tf_component.train()`

**Comment by getnamo** [comment]
It doesn't do anything automatically you'll need check it in your script to determine whether something should trigger. Example usage would be the save/load example script: https://github.com/getnamo/tensorflow-ue4-examples/blob/master/Content/Scripts/mnistSaveLoad.py#L89

**Comment by bernhardrieder** [comment]
Oh, my bad! I thought it should trigger a new training automatically.

**Comment by getnamo** [comment]
No worries, not all of the more advanced API is clearly explained and most of it came out of necessity as I was making some examples. If you have better suggestions, I'm all ears, I'm not a ML expert so feedback from real use cases would be awesome.

**Comment by bernhardrieder** [comment]
Well, I'm not an ML expert either :) I just needed the retraining in my use case because I'm generating stuff and feed the generated stuff back to the model and I wanted to retrain it after, e.g., 20 generations. But, I would create a should retrain setter so that the retraining is triggered and you don't need to care about it
