### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by getnamo** [getnamo/tensorflow-ue4#4]
Need gifs and examples of v0.1 API and expected python functions.

- [x] github API
- [x] expanded example gifs and documentation
- [ ] video
- [x] document auxiliary c++ utility functions such as texture-> float array and byte streams.
- [x] rebuild mnist beginner sample from scratch
- [ ] start with constant ops, move to placeholder, finally move to mnist beginner
- [x] include a saved model?

**Comment by chaiyuntian** [comment]
@getnamo Hi Jan, I am the community manager from Epic Games China. I would like to write some articles in Chinese to introduce some of your plugins to our Chinese Unreal Engine users. And I need you permission to translate some paragraph from your github readme and you blog into Chinese and to use some screenshot images. Sorry I was not able to find your contact else where, so I have to use the comment here, This is my email: yuntian.chai@epicgames.com. Looking forward to you reply.

**Comment by getnamo** [comment]
Answered in email. For future reference check out getnamo.com to find ways to contact me.
