### ISSUE TITLE
Commit plugin content to game repository (fails without binaries)

### ISSUE THREAD

**Issue by codewing** [getnamo/tensorflow-ue4#40]
Hey :)
I had to commit the binaries in the three plugin folders to make it work on another machine. This is obviously not preferred so I am wondering what in my setup is wrong:

## Steps to reproduce:

- Create a blueprint project
- Add a gitignore (I used [UnrealEngine.gitignore](https://github.com/github/gitignore/blob/master/UnrealEngine.gitignore) from github)
- Git init + commit for setup (just for fallbacks)
- Start the project -> Works
- Add the plugin
- Start the project again to get dependencies -> Works
- Commit all added files
- Use git clean -xdf or simply clone to another folder to simulate clean checkout
- Open the project -> Missing libaries -> Build -> Failes

## Info
 - Used the latest release (v0.11.0 for UE4.21)
- and (obviously) UE4.21.0

What am I doing wrong?

**Comment by getnamo** [comment]
See https://github.com/getnamo/tensorflow-ue4-examples which uses git submodules for each plugin and [git lfs](https://git-lfs.github.com/) for binary files which makes the initial pull faster.

If you're not familiar with submodules see https://git-scm.com/book/en/v2/Git-Tools-Submodules and https://blog.github.com/2016-02-01-working-with-submodules/ for a primer. Github desktop client supports submodules so you can skip some of the git commands.

**Comment by codewing** [comment]
Thanks for the reply!
I've removed the plugin files and added them as a submodule.
But I'm still facing the problem that ue4 doesnt open because of the missing plugins.

Unfortunately I cannot release it to the public in the current state due to the exercise restrictions of my university thus I only invited you personally. But we can still discuss the issue here if anyone faces the same issue

**Comment by getnamo** [comment]
That's the correct way, git shouldn't store binaries so if it's a blueprint project you need to download them from releases and drag and drop over.

Normally if you're using git, the project would support C++ and it would recompile the plugins when you compile the project and generate the binaries whenever you need to e.g. on an engine update.

**Comment by codewing** [comment]
Ah okay, but I am wondering why it doesnt download the dependencies on its own like it does like the time I initially added it.
Because creating another project for the binaries seems kind of weird to me. But anyway thanks for the help!
