### ISSUE TITLE
Support for 4.24 and 4.25

### ISSUE THREAD

**Issue by JernejHabjan** [getnamo/tensorflow-ue4#56]
Will there be support for UE4 4.24 and 4.25 anytime soon?

**Comment by getnamo** [comment]
I do plan to add support for those versions, just a bit busy recently. Maybe likely addressable in a couple of weeks.

**Comment by alexander-ossur** [comment]
Hi. I Second that.

Actually I tried to quick recompile this for 4.24. Unfortunately it's showing some compilation errors for UEPython.

**Comment by getnamo** [comment]
Currently working through https://github.com/getnamo/unrealenginepython changes. Will address a refactor into [MachineLearningBase](https://github.com/getnamo/machine-learning-remote-ue4/tree/master/Source/MachineLearningBase) here before making a release. Not direct ETA yet but it's being worked on.

**Comment by getnamo** [comment]
After realizing scope of UnrealEnginePython maintenance I've decided to make the transition to the machine learning remote architecture for 4.25. Early release of refactor with auto-server launching confirmed working found here: https://github.com/getnamo/tensorflow-ue4/releases/tag/1.0.0alpha2. API is currently not fully documented, but refer to https://github.com/getnamo/machine-learning-remote-ue4 for general changes

**Comment by JernejHabjan** [comment]
Thanks
