### ISSUE TITLE
Sample project in 4.26

### ISSUE THREAD

**Issue by pikumb94** [getnamo/tensorflow-ue4#65]
Hi getnamo,
I saw already other issues about 4.25+ compatibility. As I understand it, I have to follow this for now:
https://github.com/getnamo/tensorflow-ue4/issues/60

1. I download the master of tensorflow-ue4 and socketio-client-ue4 and put in a "Plugins" folder (but don't find some modules).
2. Now I installed also phyton 3.5 with tensorflow API.

What should I do now? Your tutorial on the repository page refers to the version where everything download by themself and the phyton VM is embedded in project (4.23 if I'm not wrong).
In case of a 4.26 what should I lastly do to make phyton and UE4 correctly dialogue?
I have read that you are currently working on 4.26 release (Unreal won't do any 4.27 as I know) and guide so I want to ask you if you have a schedule (e.g. before or after august) of a 4.26 sample or you're doing freely without any deadline.
I ask this since I want to start and rapidly finish a personal project and so I can decide to stay with this version or fallback to 4.23 without bothering you.
Thanks

**Comment by simonfitzy** [comment]
Hi pikumb94

Did you have any luck with getting it to work on 4.26?

Best regards
Simon
